### ISSUE TITLE
add subscription while gulel is running

### ISSUE THREAD

**Issue by LucasAdam** [abskmj/gulel#1]
Hi, thanks for this amazing app 😊 !

Is there a way to add a subscription while the gulel is already running ?

Regards

**Comment by abskmj** [comment]
Thanks for using Gulel.

I see [express already supports](https://stackoverflow.com/questions/20857865/okay-to-add-a-route-to-node-js-express-while-listening) it. Since Gulel is an express app, you should able to do it in a similar way. 

I would like to hear more about your use case.

**Comment by abskmj** [comment]
I think I got what you are talking about. Gulel, currently, automatically subscribes on server startup and therefore, the subscription doesn't work when it is already running. I can probably implement something to handle this. But, I'm curious know: is there any reason that you can't subscribe before the start up?

**Comment by LucasAdam** [comment]
I don't necessarily know all the streams I want to subscribe to when I start the bot. I'd like my discord bot to listen to commands like `!stream add streamName` and then add a new subscription to get notified whenever it goes live. I could also stop & restart gulel but i'm not sure how to stop it correctly (unsubscribe to everything) without having to type quit. I'm not sure there is an exposed method for that, is there ?

**Comment by abskmj** [comment]
Thanks, I got more insights.

I will add a way to shut down the server programmatically and a way to subscribe/unsubscribe when gulel is running.

Probably, will release a new version in a couple of days.

**Comment by LucasAdam** [comment]
That's great man thank you so much :) ! Take whatever time you need :p

**Comment by abskmj** [comment]
I have published a new version (1.1.0). You can take reference from [this example](https://github.com/abskmj/gulel/blob/master/examples/dynamic.js).
