### ISSUE TITLE
Cache Subscriptions?

### ISSUE THREAD

**Issue by choccy** [abskmj/gulel#4]
During testing I regularly in to the error: `` 'hub.mode': 'denied', 'hub.reason': 'exceeded maximum number of allowed subscriptions for topic' `` because Gulel is resubscribing to the same topic every time I restart the server and the limit is 3 according to Twitch Docs.

So maybe Gulel should cache the necessary info about what it's already done? For example it would cache the data on this specific topic on this specific server URL, and also the time when the subscription was created to see if it needs a new lease etc

Thanks for your work on this btw!

**Comment by abskmj** [comment]
Gulel is designed to unsubscribe from all active subscriptions when shutting down. It is recommended to call `gulel.shutdown()` functions when exiting the server.

**Comment by choccy** [comment]
> Gulel is designed to unsubscribe from all active subscriptions when shutting down. It is recommended to call `gulel.shutdown()` functions when exiting the server.

**Comment by choccy** [comment]
I may have accidentally clicked some wrong buttons on mobile, my bad lol.

But I have this:

```
process.on('beforeExit', function (code) {
  gulel.shutdown()
});
```

at the bottom of my script, it does not unsubscribe properly.

**Comment by abskmj** [comment]
Are you seeing these messages in the console? If not, somehow the shutdown sequence is not getting called.

```
Gulel is shutting down
Unsubscribing from active subscriptions
```

**Comment by choccy** [comment]
The message comes up but it's not unsubbing.

**Comment by abskmj** [comment]
`gulel.shutdown()` is an asynchronous function and that could be the reason. Can you update your code to below? Reference answer on [stackoverflow.com](https://stackoverflow.com/questions/40574218/how-to-perform-an-async-operation-on-exit). This would enable nodejs process to wait till the shutdown is complete.

```
process.on('beforeExit', async function () {
  await gulel.shutdown()
});
```

**Comment by choccy** [comment]
Did not make a difference, restarting the app 3 times brings it back.

**Comment by choccy** [comment]
I tried this after:

```
process.on('beforeExit', async function () {
  const subscription = gulel.getSubscription('/users/follows?first=1&to_id=369937')

  await subscription.unsubscribe()
});
```

No progress on unsubbing.

**Comment by choccy** [comment]
I've switched to another method so will be closing unless someone else gets the same problem.
